on:
    pull_request:
        branches: [main]
jobs:
    tests:
        name: Run Tests
        runs-on: ubuntu-latest
        services:
            #setsup postgres with the password postgres
            postgres:
                # Docker Hub image
                image: postgres
                # Provide the password for postgres
                env:
                    POSTGRES_PASSWORD: postgres
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    # Maps tcp port 5432 on service container to the host
                    - 5432:5432
        steps:
            #checks out repository
            - uses: actions/checkout@v4
            - name: setupNode
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: yarn install --immutable
            - name: build project
              run: yarn run build
            - name: test
              run: yarn run vitest --run
